<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="2" failed="2" ignored="0" total="4" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="88" started-at="2021-10-08T02:33:51Z" finished-at="2021-10-08T02:33:51Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="88" started-at="2021-10-08T02:33:51Z" finished-at="2021-10-08T02:33:51Z">
      <class name="com.testNgTestCases.TestNgClass3">
        <test-method status="PASS" signature="beforeSuite()[pri:0, instance:com.testNgTestCases.TestNgClass3@42e26948]" name="beforeSuite" is-config="true" duration-ms="29" started-at="2021-10-08T02:33:51Z" finished-at="2021-10-08T02:33:51Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeSuite -->
        <test-method status="PASS" signature="beforeTest()[pri:0, instance:com.testNgTestCases.TestNgClass3@42e26948]" name="beforeTest" is-config="true" duration-ms="0" started-at="2021-10-08T02:33:51Z" finished-at="2021-10-08T02:33:51Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeTest -->
        <test-method status="PASS" signature="beforeClass()[pri:0, instance:com.testNgTestCases.TestNgClass3@42e26948]" name="beforeClass" is-config="true" duration-ms="1" started-at="2021-10-08T02:33:51Z" finished-at="2021-10-08T02:33:51Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeClass -->
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:com.testNgTestCases.TestNgClass3@42e26948]" name="beforeMethod" is-config="true" duration-ms="1" started-at="2021-10-08T02:33:51Z" finished-at="2021-10-08T02:33:51Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="FAIL" signature="validateGMOonlineLoadedSuccessfully()[pri:-1, instance:com.testNgTestCases.TestNgClass3@42e26948]" name="validateGMOonlineLoadedSuccessfully" duration-ms="10" started-at="2021-10-08T02:33:51Z" finished-at="2021-10-08T02:33:51Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
at com.testNgTestCases.TestNgClass3.validateGMOonlineLoadedSuccessfully(TestNgClass3.java:38)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateGMOonlineLoadedSuccessfully -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:com.testNgTestCases.TestNgClass3@42e26948]" name="afterMethod" is-config="true" duration-ms="1" started-at="2021-10-08T02:33:51Z" finished-at="2021-10-08T02:33:51Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="SKIP" signature="ValidateOnLineCatalogLoadedSuccessfully()[pri:0, instance:com.testNgTestCases.TestNgClass3@42e26948]" name="ValidateOnLineCatalogLoadedSuccessfully" duration-ms="1" started-at="2021-10-08T02:33:51Z" depends-on-methods="com.testNgTestCases.TestNgClass3.validateGMOonlineLoadedSuccessfully" finished-at="2021-10-08T02:33:51Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TestNgClass3.ValidateOnLineCatalogLoadedSuccessfully()[pri:0, instance:com.testNgTestCases.TestNgClass3@42e26948] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TestNgClass3.ValidateOnLineCatalogLoadedSuccessfully()[pri:0, instance:com.testNgTestCases.TestNgClass3@42e26948] depends on not successfully finished methods
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:887)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ValidateOnLineCatalogLoadedSuccessfully -->
        <test-method status="SKIP" signature="ValidatePriceCalculationInPlaceorderPage()[pri:1, instance:com.testNgTestCases.TestNgClass3@42e26948]" name="ValidatePriceCalculationInPlaceorderPage" duration-ms="0" started-at="2021-10-08T02:33:51Z" depends-on-methods="com.testNgTestCases.TestNgClass3.ValidateOnLineCatalogLoadedSuccessfully" finished-at="2021-10-08T02:33:51Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TestNgClass3.ValidatePriceCalculationInPlaceorderPage()[pri:1, instance:com.testNgTestCases.TestNgClass3@42e26948] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TestNgClass3.ValidatePriceCalculationInPlaceorderPage()[pri:1, instance:com.testNgTestCases.TestNgClass3@42e26948] depends on not successfully finished methods
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:887)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ValidatePriceCalculationInPlaceorderPage -->
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:com.testNgTestCases.TestNgClass3@42e26948]" name="beforeMethod" is-config="true" duration-ms="0" started-at="2021-10-08T02:33:51Z" finished-at="2021-10-08T02:33:51Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="FAIL" signature="ValidateAllorders()[pri:2, instance:com.testNgTestCases.TestNgClass3@42e26948]" name="ValidateAllorders" duration-ms="1" started-at="2021-10-08T02:33:51Z" finished-at="2021-10-08T02:33:51Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
at com.testNgTestCases.TestNgClass3.ValidateAllorders(TestNgClass3.java:80)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ValidateAllorders -->
        <test-method status="PASS" signature="afterTest()[pri:0, instance:com.testNgTestCases.TestNgClass3@42e26948]" name="afterTest" is-config="true" duration-ms="0" started-at="2021-10-08T02:33:51Z" finished-at="2021-10-08T02:33:51Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTest -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:com.testNgTestCases.TestNgClass3@42e26948]" name="afterMethod" is-config="true" duration-ms="0" started-at="2021-10-08T02:33:51Z" finished-at="2021-10-08T02:33:51Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="afterClass()[pri:0, instance:com.testNgTestCases.TestNgClass3@42e26948]" name="afterClass" is-config="true" duration-ms="0" started-at="2021-10-08T02:33:51Z" finished-at="2021-10-08T02:33:51Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterClass -->
        <test-method status="PASS" signature="afterSuite()[pri:0, instance:com.testNgTestCases.TestNgClass3@42e26948]" name="afterSuite" is-config="true" duration-ms="0" started-at="2021-10-08T02:33:52Z" finished-at="2021-10-08T02:33:52Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterSuite -->
      </class> <!-- com.testNgTestCases.TestNgClass3 -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
